name: Build EfiGuard
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Install Assembly Tools (NASM)
        run: |
          choco install nasm
          echo "NASM_PREFIX=C:\Program Files\NASM\" >> $env:GITHUB_ENV

      - name: Checkout EDK2
        run: |
          git clone --recursive https://github.com/tianocore/edk2.git edk2
          
      - name: Checkout EfiGuard with Submodules
        run: |
          cd edk2
          git clone --recursive https://github.com/${{ github.repository }}.git EfiGuardPkg

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Compile EDK2 BaseTools
        run: |
          cd edk2
          cmd /c "edksetup.bat Rebuild"

      - name: Compile EfiGuard Binaries
        run: |
          cd edk2
          cmd /c "edksetup.bat && build -a X64 -t VS2022 -p EfiGuardPkg/EfiGuardPkg.dsc -b RELEASE"

      - name: Upload Compiled Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: EfiGuard-Latest-Fixed
          path: edk2/Build/EfiGuard/RELEASE_VS2022/X64/
